### ISSUE TITLE
purrr::compose

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#11]
In stead of using for loop, we could use compose when constructing the prompt text:

```
construct_prompt_text <- function(prompt) {
  prompt <- prompt(prompt)

  prompt_text <- get_base_prompt(prompt)

  prompt_wraps <- get_prompt_wraps_ordered(prompt)

  if (length(prompt_wraps) > 0) {
    for (i in 1:length(prompt_wraps)) {
      prompt_text <- prompt_wraps[[i]]$modify_fn(prompt_text)
    }
  }
  return(prompt_text)
}

```
https://www.rdocumentation.org/packages/purrr/versions/0.2.5/topics/compose

```
  if (length(prompt_wraps) > 0) {
    modify_fns <- map(prompt_wraps, "modify_fn")
    composed_fn <- compose(!!!modify_fns)
    prompt_text <- composed_fn(prompt_text)
  }
```

streamlines the code a little bit, however creates purrr dependancy.

**Comment by lukakoning** [comment]
Hmm ja, cleaner maar ook wat abstracter en zou zelf gaan voor zo min mogelijk dependencies. Dplyr wordt nu ook ergens gebruikt om regels toe te voegen aan chat history, liefst zou ik die dependency er ook nog uithalen. Code is dan wel iets minder mooi in base R

**Comment by tjarkvandemerwe** [comment]
Ja logisch, zijn ook wat andere opties om een list met geneste functies vanuit base te runnen:
https://stackoverflow.com/questions/17190588/apply-over-nested-functions
