### ISSUE TITLE
multiple extraction/validation functions?

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#12]
I think it would be more clear if there is only 1 function to add to extraction/validation. And we could use compose to condense lists of functions into single functions. However, I think the user automatically creates single functions to extract or validate the output.
We could also improve the naming:

```
new_wrap <- prompt_wrap(
    modify_fn = modify_fn,
    extraction_functions = list(extraction_fn),
    validation_functions = list(validation_fn)
  )
```

To:

```
new_wrap <- prompt_wrap(
    modify_fn = modify_fn,
    extract_fn = extract_fn,
    validate_fn = validate_fn
  )
```

**Comment by lukakoning** [comment]
Agreed, in practice I think you will usually only add one function, and if needed you can always create a combining function.

**Comment by lukakoning** [comment]
Done op mijn branch
