### ISSUE TITLE
prompt_wrap appends?

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#13]
Can we give the prompt_wrap function a prompt as first argument, and do the appending as well?
So instead of when creating a wrapper function you end with this:

```
new_wrap <- prompt_wrap(
    modify_fn = modify_fn
  )
append_prompt_wrap(prompt, new_wrap)
```

You end with:
`prompt_wrap(prompt, modify_fn)`

This means you can also create wrappers in a pipeline:
```
"hi" |>
  prompt_wrap(\(x) paste(x, "there"))
```

**Comment by lukakoning** [comment]
Lijkt mij een goed idee
