### ISSUE TITLE
max_retries uit send_prompt

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#20]
wordt iets op level prompt_wrap, met default vanuit prompt_wrap, functies kunnen dat aanpassen door max_retries variabele door te passen.

**Comment by lukakoning** [comment]
Argument op mijn branch eruit gehaald maar nog niet wrap-by-wrap geïmplementeerd

**Comment by lukakoning** [comment]
Closing as it is related to https://github.com/tjarkvandemerwe/tidyprompt/issues/14
