### ISSUE TITLE
send_prompt: add output besides the response, e.g., full chat history

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#21]
prompt_response object:
response
log, df met user, response
tijden

**Comment by lukakoning** [comment]
Met 980ed6b en 4104c61 nu gedaan.

Ik heb nu 2 modes ingebouwd, één is enkel response en één is list met details. De tests e..d. werken nu nog op enkel response. Volgens mij is je de base pipe gebruikt is iets als: prompt |> send_prompt(...) |> .$response |> ... ook niet mogelijk; met '%>%' kan dat wel (dus voor de base pipe is de 'only_response' mode dan nuttig als je door wil pipen met de uitkomst).

Eventuele todo is nog om response-parameters van de specifieke LLM provider ook nog door te sluisen (kan info bevatten over hoeveel tokens gebruikt bijvoorbeeld).

**Comment by tjarkvandemerwe** [comment]
conclusie: list object is default, toggle voor basic object is oke, alternatief is een send_prompt_simple oid. Tests ombouwen zodat ze met prompt_result$result om kunnen gaan, eventueel helper get_result() zodat je het in een pipeline eruit kan halen.

**Comment by lukakoning** [comment]
Ik heb nu met 33a6c952448f15896eb8d830d4e1f8f2a737bf85 het zo gemaakt dat de volledige http responses van providers ook kunnen worden meegegeven

**Comment by lukakoning** [comment]
Met 1dec90c wordt ook nog clean chat history meegegeven
