### ISSUE TITLE
deploy pkgdown site

### ISSUE THREAD

**Issue by lukakoning** [tjarkvandemerwe/tidyprompt#26]
Als je naar Settings (van repository) > Pages gaat, instellen:

**Source:**
Deploy from branch
**Branch:**
Main; /docs

Dan zou het moeten werken op de URL. Er is ook een manier om het met github actions te deployen vanaf de gh-pages branch, maar dat lukte mij nog niet helemaal. Dit is in ieder geval simpel en werkt.

**Comment by tjarkvandemerwe** [comment]
done, ook opnieuw de build_site gerunt, werkt nu volgens mij!
