### ISSUE TITLE
Meer pre-built prompt-wraps, integreren helper functies

### ISSUE THREAD

**Issue by lukakoning** [tjarkvandemerwe/tidyprompt#28]
@tjarkvandemerwe Nu de eerdere punten zo'n beetje zijn weggewerkt hebben we denk ik een aardige basis voor het package. 

We kunnen het wellicht nog 1x reviewen en dan ons gaan richten op het implementeren van een aantal handige pre-built prompt_wraps, + het toevoegen van wat helper-functies uit het llm-project (df to string, etc.)?

Dan kunnen we daarna het package gaan toepassen in het project & ook binnenkort een alpha version submitten naar bijv. CRAN

**Comment by tjarkvandemerwe** [comment]
answer_as_list
answer_as_logical
answer_as_code

answer_by_react

object_to_string?
list_to_string
vector_to_string

**Comment by lukakoning** [comment]
Ik ben bezig met answer as code

**Comment by lukakoning** [comment]
Answer_as_code geïmplementeerd met e957318765bb437dd9d38fa981bf96c5061cb4c8

**Comment by lukakoning** [comment]
Answer as list gedaan met 50881fe

**Comment by lukakoning** [comment]
Answer as named list gedaan met 27770bc

**Comment by lukakoning** [comment]
Answer as boolean gedaan met c98caa8

**Comment by lukakoning** [comment]
Answer by react gedaan met 3e98eeb

**Comment by lukakoning** [comment]
Answer_by_regex ook gedaan

**Comment by lukakoning** [comment]
quit_if met d96da4f
