### ISSUE TITLE
rename prompt naar tidyprompt

### ISSUE THREAD

**Issue by lukakoning** [tjarkvandemerwe/tidyprompt#29]
fixt namespace issue

**Comment by lukakoning** [comment]
vgm done, ik heb op jouw changes nog even devtools::check() en paar restanten van 'prompt' op die manier gevonden en gefixt

**Comment by tjarkvandemerwe** [comment]
nice! ik heb ook wat foutjes er nog uitgeplukt die tijdens het builden naar boven kwamen. De build errors komen nu vanuit een andere hoek, volgens mij zitten bepaalde tests er nog niet helemaal stabiel in. Maar is dit ding opgelost.
