### ISSUE TITLE
fix ollama stream issue

### ISSUE THREAD

**Issue by lukakoning** [tjarkvandemerwe/tidyprompt#38]

**Comment by lukakoning** [comment]
Needs verification of fix @tjarkvandemerwe

**Comment by tjarkvandemerwe** [comment]
werkt! mijn enige vraag is waarom de default NULL is ipv FALSE, of laat je het dan afhangen van de provider?

**Comment by lukakoning** [comment]
Ja klopt, de setting uit de provider is leidend. (die hebben wel default values). Maar send_prompt kan deze setting overrulen met TRUE/FALSE (i.p.v. NULL)
