### ISSUE TITLE
answer_as_integer: add_instruction_to_prompt = FALSE unclear

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#4]
In de functie answer_as_integer, waarom is de default value voor de instructie toevoegen aan de prompt FALSE? Wil je juist niet dat de modification function altijd de prompt aanpast? Of gebeurt dat op een andere plek? En is dit wel een setting die we aanpasbaar willen maken?

```
answer_as_integer <- function(
    prompt_wrap_or_list, min = NULL, max = NULL, add_instruction_to_prompt = FALSE
)
```

**Comment by lukakoning** [comment]
'TRUE' is inderdaad logischer; klopt! Verder had ik deze optie vooral even toegevoegd om een fout op validatie te triggeren (om te testen of dat werkte), vandaar

**Comment by tjarkvandemerwe** [comment]
6cab1af5706bd01837e7882fabe4bea7da889a92 fix
