### ISSUE TITLE
increase context window Ollama

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#48]
ollama /set parameter num_ctx 4096

Kunnen we dit gebruiken wanneer we zoiets doen:
llm_con$parameters$num_ctx <- 4096

**Comment by lukakoning** [comment]
Dit werkt nu:

ollama$parameters$options$num_ctx <- 4096

Bij ollama (i.t.t. OpenAI API-types) zitten dergelijke opties in een list 'options' binnen de parameters
