### ISSUE TITLE
prompt shows empty when adding tool

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#49]
"hello, what folders are there in this directory?" |> add_tools(tool_functions = list(dir))

results in:
<tidyprompt>
The base prompt is modified by a prompt wrap, resulting in:
>  
Use '<tidyprompt>$prompt_wraps' to show the prompt wraps.
Use '<tidyprompt>$base_prompt' to show the base prompt text.
Use '<tidyprompt> |> construct_prompt_text()' to get the full prompt text.

Volgens mij omdat hij geen results krijgt van:
add_tools_extract_documentation()

Ik denk dat we een functie nodig hebben die het van base/package functies doet?

**Comment by lukakoning** [comment]
Geimplementeerd met 518b1abf09fc08a927f4d7ba2be972b1b85217d9
