### ISSUE TITLE
pkgdown 2

### ISSUE THREAD

**Issue by lukakoning** [tjarkvandemerwe/tidyprompt#55]
Deze error krijgt de gh-pages branch:  

Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir0 - /github/workspace/docs
                    
Mogelijk moet je bij de Github pages settings 'root' selecteren ipv 'docs' --- zie: https://github.com/orgs/community/discussions/76938

Kan je dat proberen @tjarkvandemerwe?

**Comment by tjarkvandemerwe** [comment]
done

**Comment by lukakoning** [comment]
Super, het werkt nu; is de site dus altijd up-to-date met de main branch!
