### ISSUE TITLE
answer_as_list

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#56]
does not return vector anymore:

```
"Can you name me five fruits?" |> 
  answer_as_list() |> 
  send_prompt(ollama)
```

Returns:
"Here are five fruits:\n\n  1. Apple\n  2. Banana\n  3. Strawberry\n  4. Orange\n  5. Mango"

And there is no validation/extraction error/retry.

**Comment by tjarkvandemerwe** [comment]
In last update it returns a list, however with one object.

**Comment by lukakoning** [comment]
Top, dit werkt inderdaad ook als LLM besluit te scheiden met '\n' i.p.v. ','

**Comment by lukakoning** [comment]
merged pr
