### ISSUE TITLE
user profile and system profile prevent r_session from starting

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#59]
Experienced timeouts when using the answer_as_code wrapper, happened when creating new session, does not happen with the following addition:

opts <- callr::r_session_options()
opts$user_profile <- FALSE
opts$system_profile <- FALSE
evaluation_session <- callr::r_session$new(options = opts)

user/system profiles can interupt the session creation, maybe by default ignore the profiles and create a clean environment without the interference of these profiles.

**Comment by lukakoning** [comment]
1aa59ecbb07596f746378a83e5098540c303c641
