### ISSUE TITLE
naming of add_tools

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#6]
add_tools klinkt heel generiek, maar eigenlijk geef je een zelf gedefinieerde functie mee aan het model.
Ik kan me voorstellen dat we ook add_tool_package oid krijgen, waarbij je een r package met alle functies beschikbaar maakt voor het model of add_tool_r, waarbij je gewoon zegt, run maar wat random R code, en dan krijg je daar de resultaten van.

Is dit iets om de naamgeving op voor te bereiden?

**Comment by lukakoning** [comment]
Hmmm ja, even over nadenken.

Bij add_tools zoals nu zou je in ieder geval een lijst functies meegeven, niet al te veel, want anders wordt de prompt te groot.

Als je toegang tot een geheel R package wil geven denk je meer aan code extraction, en een r-sessie op de achtergrond starten, die je in je prompt dan ook beschrijft. Dan beschrijf je niet per se individuele functies maar de r-sessie (objects in environment, welke packages zijn loaded).

Ik denk dat allebei interessant zou zijn om aan te bieden in dit package.

Misschien iets als add_r_functions en/of add_r_session

**Comment by lukakoning** [comment]
Wellicht: rename huidige add tool naar answer_with_r_function of answer_using_r_function?

**Comment by lukakoning** [comment]
Achteraf bezien denk ik dat eigenlijk alle use cases wel binnen de huidige 'add_tools' kunnen worden uitgewerkt, als (stateful) functies. Voorlopig zou ik het dus houden zoals het nu is
