### ISSUE TITLE
json prompts extract return code blocks

### ISSUE THREAD

**Issue by tjarkvandemerwe** [tjarkvandemerwe/tidyprompt#66]
I noticed that many of the JSON responses are returned in this format:
\```json
\<json object>
\```
However the JSON extraction function looks for the underlying JSON object itself. Would it be more robust to add the following regex first?
`llm_response  <- str_extract_all(llm_response, "(?s)(?<=```json)(.*?)(?=```)")`
To differentiate between the real JSON object and examples/explanations?

**Comment by lukakoning** [comment]
I tend to also get json objects without the tags (depends on the model and prompt most I suppose), so it could also create problems if we only extract from within the tags. I haven't encountered problems so far with the current method. Could add a toggle, but atm I don't really think it's necesarry
